# Generated by Django 5.1.4 on 2025-01-14 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmock_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='is_finished',
        ),
        migrations.CreateModel(
            name='StudentTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_finished', models.BooleanField(default=False)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolmock_app.test')),
                ('test_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_test', to='schoolmock_app.test')),
            ],
        ),
    ]
