# Generated by Django 5.1.4 on 2025-01-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmock_app', '0002_remove_studentanswer_is_finished_studenttest'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='StudentTest',
        ),
    ]
