# Generated by Django 5.1.4 on 2025-01-18 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmock_app', '0004_studenttest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentTest',
        ),
    ]
